import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.histplot(df['global_avg_temperature'], kde=True)
plt.title('Distribution of Global Average Temperature')
plt.xlabel('Global Average Temperature')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(15, 8))
sns.boxplot(x='country', y='global_avg_temperature', data=df)
plt.title('Global Average Temperature Distribution by Country')
plt.xlabel('Country (Encoded)')
plt.ylabel('Global Average Temperature')
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='global_avg_temperature', y='climate_risk_index', data=df)
plt.title('Global Average Temperature vs. Climate Risk Index')
plt.xlabel('Global Average Temperature')
plt.ylabel('Climate Risk Index')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='global_avg_temperature', data=df)
plt.title('Global Average Temperature Over Years')
plt.xlabel('Year')
plt.ylabel('Global Average Temperature (°C)')
plt.grid(True)
plt.show()

plt.figure(figsize=(16, 12))
sns.heatmap(df[num_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numerical Features')
plt.show()

sns.pairplot(df[['global_avg_temperature', 'climate_risk_index', 'co2_concentration_ppm', 'sea_level_rise_mm']])
plt.suptitle('Pairplot of Selected Numerical Features', y=1.02) # Adjust suptitle position
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='co2_concentration_ppm', y='global_avg_temperature', data=df)
plt.title('CO2 Concentration vs. Global Average Temperature')
plt.xlabel('CO2 Concentration (ppm)')
plt.ylabel('Global Average Temperature (°C)')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='sea_level_rise_mm', data=df)
plt.title('Sea Level Rise Over Years')
plt.xlabel('Year')
plt.ylabel('Sea Level Rise (mm)')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['deforestation_rate'], kde=True)
plt.title('Distribution of Deforestation Rate')
plt.xlabel('Deforestation Rate')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='annual_rainfall_mm', y='drought_index', data=df)
plt.title('Annual Rainfall vs. Drought Index')
plt.xlabel('Annual Rainfall (mm)')
plt.ylabel('Drought Index')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['air_quality_index'], kde=True)
plt.title('Distribution of Air Quality Index')
plt.xlabel('Air Quality Index')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='fossil_fuel_consumption', y='renewable_energy_share', data=df)
plt.title('Fossil Fuel Consumption vs. Renewable Energy Share')
plt.xlabel('Fossil Fuel Consumption')
plt.ylabel('Renewable Energy Share')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='sea_surface_temperature', data=df)
plt.title('Sea Surface Temperature Over Years')
plt.xlabel('Year')
plt.ylabel('Sea Surface Temperature')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['heatwave_days'], kde=True)
plt.title('Distribution of Heatwave Days')
plt.xlabel('Heatwave Days')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='temperature_anomaly', data=df)
plt.title('Temperature Anomaly Over Years')
plt.xlabel('Year')
plt.ylabel('Temperature Anomaly')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['flood_events_count'], kde=True)
plt.title('Distribution of Flood Events Count')
plt.xlabel('Flood Events Count')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='max_temperature', data=df)
plt.title('Maximum Temperature Over Years')
plt.xlabel('Year')
plt.ylabel('Maximum Temperature')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['min_temperature'], kde=True)
plt.title('Distribution of Minimum Temperature')
plt.xlabel('Minimum Temperature')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='forest_cover_percent', data=df)
plt.title('Forest Cover Percentage Over Years')
plt.xlabel('Year')
plt.ylabel('Forest Cover Percentage')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['predicted_temperature_2050'], kde=True)
plt.title('Distribution of Predicted Temperature in 2050')
plt.xlabel('Predicted Temperature 2050')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='co2_concentration_ppm', y='climate_risk_index', data=df)
plt.title('CO2 Concentration vs. Climate Risk Index')
plt.xlabel('CO2 Concentration (ppm)')
plt.ylabel('Climate Risk Index')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['drought_index'], kde=True)
plt.title('Distribution of Drought Index')
plt.xlabel('Drought Index')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='drought_index', data=df)
plt.title('Drought Index Over Years')
plt.xlabel('Year')
plt.ylabel('Drought Index')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='annual_rainfall_mm', y='drought_index', data=df)
plt.title('Annual Rainfall vs. Drought Index')
plt.xlabel('Annual Rainfall (mm)')
plt.ylabel('Drought Index')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['annual_rainfall_mm'], kde=True)
plt.title('Distribution of Annual Rainfall (mm)')
plt.xlabel('Annual Rainfall (mm)')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['fossil_fuel_consumption'], kde=True)
plt.title('Distribution of Fossil Fuel Consumption')
plt.xlabel('Fossil Fuel Consumption')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['fossil_fuel_consumption'], kde=True)
plt.title('Distribution of Fossil Fuel Consumption')
plt.xlabel('Fossil Fuel Consumption')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='renewable_energy_share', y='climate_risk_index', data=df)
plt.title('Renewable Energy Share vs. Climate Risk Index')
plt.xlabel('Renewable Energy Share')
plt.ylabel('Climate Risk Index')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='deforestation_rate', data=df)
plt.title('Deforestation Rate Over Years')
plt.xlabel('Year')
plt.ylabel('Deforestation Rate')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='air_quality_index', y='climate_risk_index', data=df)
plt.title('Air Quality Index vs. Climate Risk Index')
plt.xlabel('Air Quality Index')
plt.ylabel('Climate Risk Index')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['forest_cover_percent'], kde=True)
plt.title('Distribution of Forest Cover Percentage')
plt.xlabel('Forest Cover Percentage')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='deforestation_rate', y='climate_risk_index', data=df)
plt.title('Deforestation Rate vs. Climate Risk Index')
plt.xlabel('Deforestation Rate')
plt.ylabel('Climate Risk Index')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='climate_risk_index', data=df)
plt.title('Climate Risk Index Over Years')
plt.xlabel('Year')
plt.ylabel('Climate Risk Index')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='annual_rainfall_mm', y='forest_cover_percent', data=df)
plt.title('Annual Rainfall vs. Forest Cover Percentage')
plt.xlabel('Annual Rainfall (mm)')
plt.ylabel('Forest Cover Percentage')
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='year', y='fossil_fuel_consumption', data=df)
plt.title('Fossil Fuel Consumption Over Years')
plt.xlabel('Year')
plt.ylabel('Fossil Fuel Consumption')
plt.grid(True)
plt.show()
